package com.hospital.enums;

public enum Specialty {
    GENERAL_PRACTICE,
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    NEUROLOGY,
    ONCOLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    PSYCHIATRY,
    RADIOLOGY,
    SURGERY,
    UROLOGY,
    GYNECOLOGY,
    OPHTHALMOLOGY,
    ENT,
    PULMONOLOGY,
    RHEUMATOLOGY,
    NEPHROLOGY,
    INFECTIOUS_DISEASE
}
